'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { UserContextProvider } from "@/hooks/user/user";
import AuthGuard from "@/guard/authGuard/authGuard";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
});
export default function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen h-screen relative`}>
        <QueryClientProvider client={queryClient}>
          <UserContextProvider>
            <AuthGuard>{children}</AuthGuard>
          </UserContextProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
